version: '3.8'

services:
  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    command: npm run serve
    network_mode: "host"

  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    network_mode: "host"

  db:
    image: postgres:16
    container_name: postgresdb
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    network_mode: "host"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    network_mode: "host"

volumes:
  db-data: