name: Deploy Frontend Application

on:
  push:
    branches:
        - develop
        - main

jobs:
  build-and-package-frontend:
    runs-on: ubuntu-latest
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Vue.js Application
        run: npm run build
        working-directory: frontend
      
      - name: List output files
        run: ls -al frontend/dist
      - name: Create deployment artifact for frontend
        run: |
          cd frontend/dist
          tar -czf myVueApp.tar.gz .
        working-directory: ..

      - name: Store frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: vue-app-build
          path: myVueApp.tar.gz

      - name: Export deployment matrix
        id: export-deployment-matrix
        run: |
          JSON="$(cat ./frontend-deployment-config.json)"
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "::set-output name=deployment-matrix::$JSON"
        working-directory: frontend

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-package-frontend
    strategy:
      matrix:
        server: ${{ fromJson(needs.build-and-package-frontend.outputs.deployment-matrix) }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: vue-app-build

      - name: Upload and Deploy Frontend
        uses: appleboy/scp-action@master
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ matrix.server.port }}
          source: myVueApp.tar.gz
          target: ${{ matrix.server.path }}/artifacts

      - name: Extract and Setup Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ matrix.server.port }}
          script: |
            mkdir -p "${{ matrix.server.path }}/releases/myVueApp"
            tar xzf ${{ matrix.server.path }}/artifacts/myVueApp.tar.gz -C "${{ matrix.server.path }}/releases/myVueApp"
