name: dockerize Database

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and Push Database
        uses: docker/build-push-action@v3
        with:
          context: backend/DB
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextgenera:version2
