name: CI Workflow

on: push 
jobs:
 frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Recommended to use LTS version, adjust as needed

      - name: Install dependencies
        run: |
          cd frontend  # Adjust this to your frontend directory
          npm install

      - name: Run lint
        run: |
          cd frontend  # Adjust this to your frontend directory
          npm run lint

      - name: Run tests
        run: |
          cd frontend  # Adjust this to your frontend directory
          npm run test

      - name: Build
        run: |
          cd frontend  # Adjust this to your frontend directory
          npm run build
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: frontend/dist  # Adjust path according to your build output directory
