name: CI Workflow

on:
  push:
   

jobs:

  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_pgsql
          tools: composer:v2, phpunit

      - name: Install PHP dependencies
        run: |
          cd "backend"
          composer install --prefer-dist --no-progress --no-suggest
      - name: Copy .env file
        run: |
          cd "backend"
          cp .env.example .env
      - name: Generate key
        run: |
          cd "backend"
          php artisan key:generate
      - name: Run migration
        run: |
          cd "backend"
          php artisan migrate
      - name: Run backend tests
        run: |
          cd "backend"
          php artisan test
