name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-Docker:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push Frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextgenera:version

      - name: Docker Build and Push Backend
        uses: docker/build-push-action@v3
        with:
          context: backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextgenera:version1

      - name: Pull and Tag PostgreSQL Image
        run: |
          docker pull postgres:15
          docker tag postgres:15 ${{ secrets.DOCKER_USERNAME }}/nextgenera:postgres-version2

      - name: Push PostgreSQL Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nextgenera:postgres-version2
